/*
 * Literal.cpp
 *
 *  Created on: 22 déc. 2014
 *      Author: FrancisANDRE
 */

#include "als/psap/Literal.h"

namespace ALS {
namespace PSAP {
/** The Literal P-SYNC-MAJOR.INDICATION. */
const char* Literal::P_SYNC_MAJOR_INDICATION = "P-SYNC-MAJOR.INDICATION";

/** The Literal P-SYNC-MINOR.INDICATION. */
const char* Literal::P_SYNC_MINOR_INDICATION = "P-SYNC-MINOR.INDICATION";

/** The Literal P-RESYNCHRONIZE.INDICATION. */
const char* Literal::P_RESYNCHRONIZE_INDICATION = "P-RESYNCHRONIZE.INDICATION";

/** The Literal P-SYNC-MINOR.CONFIRMATION. */
const char* Literal::P_SYNC_MINOR_CONFIRMATION = "P-SYNC-MINOR.CONFIRMATION";

/** The Literal P-SYNC-MAJOR.CONFIRMATION. */
const char* Literal::P_SYNC_MAJOR_CONFIRMATION = "P-SYNC-MAJOR.CONFIRMATION";

/** The Literal P-RESYNCHRONIZE.CONFIRMATION. */
const char* Literal::P_RESYNCHRONIZE_CONFIRMATION = "P-RESYNCHRONIZE.CONFIRMATION";

/** The Literal P-TOKEN-GIVE.INDICATION. */
const char* Literal::P_TOKEN_GIVE_INDICATION = "P-TOKEN-GIVE.INDICATION";

/** The Literal P-TOKEN-PLEASE.INDICATION. */
const char* Literal::P_TOKEN_PLEASE_INDICATION = "P-TOKEN-PLEASE.INDICATION";

/** The Literal P-CONTROL-GIVE.INDICATION. */
const char* Literal::P_CONTROL_GIVE_INDICATION = "P-CONTROL-GIVE.INDICATION";

/** The Literal P-ABORT.INDICATION. */
const char* Literal::P_U_ABORT_INDICATION = "P-U-ABORT.INDICATION";

/** The Literal P-ABORT.INDICATION. */
const char* Literal::P_P_ABORT_INDICATION = "P-P-ABORT.INDICATION";

/** The literal P-ACTIVITY_INTERRUPT.CONFIRMATION */
const char* Literal::P_ACTIVITY_INTERRUPT_CONFIRMATION = "P-ACTIVITY-INTERRUPT.CONFIRMATION";

/** The literal P-ACTIVITY-DISCARD.CONFIRMATION. */
const char* Literal::P_ACTIVITY_DISCARD_CONFIRMATION = "P-ACTIVITY-DISCARD.CONFIRMATION";

/** The literal P-ACTIVITY-END.CONFIRMATION. */
const char* Literal::P_ACTIVITY_END_CONFIRMATION = "P-ACTIVITY-END.CONFIRMATION";

/** The literal P-ACTIVITY-START.INDICATION. */
const char* Literal::P_ACTIVITY_START_INDICATION = "P-ACTIVITY-START.INDICATION";

/** The literal P-ACTIVITY-RESUME.INDICATION. */
const char* Literal::P_ACTIVITY_RESUME_INDICATION = "P-ACTIVITY-RESUME.INDICATION";

/** The literal P-ACTIVITY-INTERRUPT.INDICATION. */
const char* Literal::P_ACTIVITY_INTERRUPT_INDICATION = "P-ACTIVITY-INTERRUPT.INDICATION";

/** The literal P-ACTIVITY-DISCARD.INDICATION. */
const char* Literal::P_ACTIVITY_DISCARD_INDICATION = "P-ACTIVITY-DISCARD.INDICATION";

/** The literal P-ACTIVITY-END.INDICATION. */
const char* Literal::P_ACTIVITY_END_INDICATION = "P-ACTIVITY-END.INDICATION";

/** The char* P-DATA.INDICATION. */
const char* Literal::P_DATA_INDICATION = "P-DATA.INDICATION";

/** The char* P-EXPEDITED-DATA.INDICATION. */
const char* Literal::P_EXPEDITED_DATA_INDICATION = "P-EXPEDITED-DATA.INDICATION";

/** The char* P-TYPED-DATA.INDICATION. */
const char* Literal::P_TYPED_DATA_INDICATION = "P-TYPED-DATA.INDICATION";

/** The char* P-CAPABILITY-DATA.INDICATION. */
const char* Literal::P_CAPABILITY_DATA_INDICATION = "P-CAPABILITY-DATA.INDICATION";

/** The char* P-CAPABILITY-DATA.CONFIRMATION. */
const char* Literal::P_CAPABILITY_DATA_CONFIRMATION = "P-CAPABILITY-DATA.CONFIRMATION";

/** The Literal P-U-ABORT.REQUEST. */
const char* Literal::P_U_ABORT_REQUEST = "P-U-ABORT.REQUEST";

/** The Literal P-P-ABORT.REQUEST. */
const char* Literal::P_P_ABORT_REQUEST = "P-P-ABORT.REQUEST";

/** The Literal P-RELEASE.REQUEST. */
const char* Literal::P_RELEASE_REQUEST = "P-RELEASE.REQUEST";

/** The Literal P-RELEASE.RESPONSE. */
const char* Literal::P_RELEASE_RESPONSE = "P-RELEASE.RESPONSE";

/** The Literal P-RELEASE-RETRY.REQUEST. */
const char* Literal::P_RELEASE_RETRY_REQUEST = "P-RELEASE-RETRY.REQUEST";

/** The Literal P-CAPABILITY-DATA.REQUEST. */
const char* Literal::P_CAPABILITY_DATA_REQUEST = "P-CAPABILITY-DATA.REQUEST";

/** The Literal P-CAPABILITY-DATA.RESPONSE. */
const char* Literal::P_CAPABILITY_DATA_RESPONSE = "P-CAPABILITY-DATA.RESPONSE";

/** The Literal P-DATA.REQUEST. */
const char* Literal::P_DATA_REQUEST = "P-DATA.REQUEST";

/** The Literal P-EXPEDITED-DATA.REQUEST. */
const char* Literal::P_EXPEDITED_DATA_REQUEST = "P-EXPEDITED-DATA.REQUEST";

/** The Literal P-TYPED-DATA.REQUEST. */
const char* Literal::P_TYPED_DATA_REQUEST = "P-TYPED-DATA.REQUEST";

/** The Literal P-SEND.REQUEST. */
const char* Literal::P_SEND_REQUEST = "P-SEND.REQUEST (segmented)";

/** The Literal P-WRITE.REQUEST. */
const char* Literal::P_WRITE_REQUEST = "P-WRITE.REQUEST (pseudo)";

/** The literal P-U-EXCEPTION-REPORT.INDICATION. */
const char* Literal::P_U_EXCEPTION_REPORT_INDICATION = "P-U-EXCEPTION-REPORT.INDICATION";

/** The literal P-P-EXCEPTION-REPORT.INDICATION. */
const char* Literal::P_P_EXCEPTION_REPORT_INDICATION = "P-P-EXCEPTION-REPORT.INDICATION";

/** The Literal P-U-EXCEPTION-REPORT.REQUEST. */
const char* Literal::P_U_EXCEPTION_REPORT_REQUEST = "P-U-EXCEPTION-REPORT.REQUEST";

/** The Literal P-P-EXCEPTION-REPORT.REQUEST. */
const char* Literal::P_P_EXCEPTION_REPORT_REQUEST = "P-P-EXCEPTION-REPORT.REQUEST";

/** The Literal P-CONNECT.REQUEST. */
const char* Literal::P_CONNECT_REQUEST = "P-CONNECT.REQUEST";

/** The Literal P-CONNECT.INDICATION. */
const char* Literal::P_CONNECT_INDICATION = "P-CONNECT.INDICATION";

/** The Literal P-CONNECT.RESPONSE. */
const char* Literal::P_CONNECT_RESPONSE = "P-CONNECT.RESPONSE";

/** The literal P-CONNECT.CONFIRMATION */
const char* Literal::P_CONNECT_CONFIRMATION = "P-CONNECT.CONFIRMATION";

/** The Literal P-ALTER-CONTEXT.REQUEST. */
const char* Literal::P_ALTER_CONTEXT_REQUEST = "P-ALTER-CONTEXT.REQUEST";

/** The Literal P-ALTER-CONTEXT.INDICATION. */
const char* Literal::P_ALTER_CONTEXT_INDICATION = "P-ALTER-CONTEXT.INDICATION";

/** The Literal P-ALTER-CONTEXT.RESPONSE. */
const char* Literal::P_ALTER_CONTEXT_RESPONSE = "P-ALTER-CONTEXT.RESPONSE";

/** The literal P-ALTER-CONTEXT.CONFIRMATION */
const char* Literal::P_ALTER_CONTEXT_CONFIRMATION = "P-ALTER-CONTEXT.CONFIRMATION";

/** The Literal P-READ.REQUEST. */
const char* Literal::P_READ_REQUEST = "P-READ.REQUEST";

/** The Literal P-RESYNCHRONIZE.REQUEST. */
const char* Literal::P_RESYNCHRONIZE_REQUEST = "P-RESYNCHRONIZE.REQUEST";

/** The Literal P-RESYNCHRONIZE.RESPONSE. */
const char* Literal::P_RESYNCHRONIZE_RESPONSE = "P-RESYNCHRONIZE.RESPONSE";

/** The Literal P-SYNC-MAJOR_REQUEST. */
const char* Literal::P_SYNC_MAJOR_REQUEST = "P-SYNC-MAJOR.REQUEST";

/** The Literal P-SYNC-MINOR.REQUEST. */
const char* Literal::P_SYNC_MINOR_REQUEST = "P-SYNC-MINOR.REQUEST";

/** The Literal P-SYNC-MAJOR.RESPONSE. */
const char* Literal::P_SYNC_MAJOR_RESPONSE = "P-SYNC-MAJOR.RESPONSE";

/** The Literal P-SYNC-MINOR.RESPONSE. */
const char* Literal::P_SYNC_MINOR_RESPONSE = "P-SYNC-MINOR.RESPONSE";

/** The Literal P-CONTROL-GIVE.REQUEST. */
const char* Literal::P_CONTROL_GIVE_REQUEST = "P-CONTROL-GIVE.REQUEST";

/** The Literal P-TOKEN-GIVE.REQUEST. */
const char* Literal::P_TOKEN_GIVE_REQUEST = "P-TOKEN-GIVE.REQUEST";

/** The Literal P-TOKEN-PLEASE.REQUEST. */
const char* Literal::P_TOKEN_PLEASE_REQUEST = "P-TOKEN-PLEASE.REQUEST";

/** The Literal P-ACTIVITY-DISCARD.REQUEST. */
const char* Literal::P_ACTIVITY_DISCARD_REQUEST = "P-ACTIVITY-DISCARD.REQUEST";

/** The Literal P-ACTIVITY-DISCARD.RESPONSE. */
const char* Literal::P_ACTIVITY_DISCARD_RESPONSE = "P-ACTIVITY-DISCARD.RESPONSE";

/** The Literal P-ACTIVITY-END.REQUEST. */
const char* Literal::P_ACTIVITY_END_REQUEST = "P-ACTIVITY-END.REQUEST";

/** The Literal P-ACTIVITY-END.RESPONSE. */
const char* Literal::P_ACTIVITY_END_RESPONSE = "P-ACTIVITY-END.RESPONSE";

/** The Literal P-ACTIVITY-INTERRUPT.REQUEST. */
const char* Literal::P_ACTIVITY_INTERRUPT_REQUEST = "P-ACTIVITY-INTERRUPT.REQUEST";

/** The Literal P-ACTIVITY-INTERRUPT.RESPONSE. */
const char* Literal::P_ACTIVITY_INTERRUPT_RESPONSE = "P-ACTIVITY-INTERRUPT.RESPONSE";

/** The Literal P-ACTIVITY-RESUME.REQUEST. */
const char* Literal::P_ACTIVITY_RESUME_REQUEST = "P-ACTIVITY-RESUME.REQUEST";

/** The Literal P-ACTIVITY-START.REQUEST. */
const char* Literal::P_ACTIVITY_START_REQUEST = "P-ACTIVITY-START.REQUEST";

/** The Literal P-RELEASE.INDICATION. */
const char* Literal::P_RELEASE_INDICATION = "P-RELEASE.INDICATION";

/** The Literal P-RELEASE.CONFIRMATION. */
const char* Literal::P_RELEASE_CONFIRMATION = "P-RELEASE.CONFIRMATION";

}
}
